// Generated by gencpp from file pid/pid_msg.msg
// DO NOT EDIT!


#ifndef PID_MESSAGE_PID_MSG_H
#define PID_MESSAGE_PID_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pid
{
template <class ContainerAllocator>
struct pid_msg_
{
  typedef pid_msg_<ContainerAllocator> Type;

  pid_msg_()
    : header()
    , actual_accel(0.0)
    , actual_steer(0.0)
    , actual_brake(0.0)  {
    }
  pid_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , actual_accel(0.0)
    , actual_steer(0.0)
    , actual_brake(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _actual_accel_type;
  _actual_accel_type actual_accel;

   typedef float _actual_steer_type;
  _actual_steer_type actual_steer;

   typedef float _actual_brake_type;
  _actual_brake_type actual_brake;




  typedef boost::shared_ptr< ::pid::pid_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pid::pid_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pid_msg_

typedef ::pid::pid_msg_<std::allocator<void> > pid_msg;

typedef boost::shared_ptr< ::pid::pid_msg > pid_msgPtr;
typedef boost::shared_ptr< ::pid::pid_msg const> pid_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pid::pid_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pid::pid_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pid': ['/home/abhishek/catkin_ws/src/pid/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pid::pid_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pid::pid_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pid::pid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pid::pid_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid::pid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid::pid_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pid::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7471688fc81dda7cfcf18609748b819";
  }

  static const char* value(const ::pid::pid_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7471688fc81dda7ULL;
  static const uint64_t static_value2 = 0xcfcf18609748b819ULL;
};

template<class ContainerAllocator>
struct DataType< ::pid::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pid/pid_msg";
  }

  static const char* value(const ::pid::pid_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pid::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 actual_accel\n\
float32 actual_steer\n\
float32 actual_brake\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pid::pid_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pid::pid_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.actual_accel);
      stream.next(m.actual_steer);
      stream.next(m.actual_brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pid::pid_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pid::pid_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "actual_accel: ";
    Printer<float>::stream(s, indent + "  ", v.actual_accel);
    s << indent << "actual_steer: ";
    Printer<float>::stream(s, indent + "  ", v.actual_steer);
    s << indent << "actual_brake: ";
    Printer<float>::stream(s, indent + "  ", v.actual_brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PID_MESSAGE_PID_MSG_H
